package repository

import (
	"encoding/json"
)

// KeyValuePair has the stored entity in addition to an autogenerated id
type KeyValuePair struct {
	Key   string      `json:"key"`
	Value interface{} `json:"value"`
}

// KeyValueRepo is a very generic repository which accepts any type
type KeyValueRepo interface {
	FindAll() ([]KeyValuePair, error)
	Save(key string, in interface{}) (KeyValuePair, error)
	Delete(key string) error
	Find(key string) (KeyValuePair, error)
}

// ToJSON converts struct to json string
func (keyValuePair *KeyValuePair) ToJSON() (string, error) {
	byteArray, err := json.Marshal(keyValuePair)
	json := string(byteArray)

	return json, err
}
